# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: false
cache: packages

env:
  - NOT_CRAN=true

r_build_args: '--no-build-vignettes'
r_check_args: '--as-cran --ignore-vignettes'  

r:

# - 3.2
- 3.3
- 3.4
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'
